# Generated by Django 4.1.10 on 2023-12-27 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cloud_pilot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='netboxconfiguration',
            name='license',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(40), django.core.validators.MaxLengthValidator(40)]),
        ),
    ]
