# Generated by Django 4.1.10 on 2023-12-24 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cloud_pilot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='netboxconfiguration',
            options={'verbose_name': 'NetBox Configuration', 'verbose_name_plural': 'NetBox Configurations'},
        ),
        migrations.AddField(
            model_name='netboxconfiguration',
            name='env_name',
            field=models.CharField(default='', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
            preserve_default=False,
        ),
    ]
