# Generated by Django 4.1.10 on 2023-12-26 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cloud_pilot', '0002_alter_netboxconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='netboxconfiguration',
            name='env_name_storage',
            field=models.CharField(blank=True, max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='netboxconfiguration',
            name='env_name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
