# Generated by Django 4.1.10 on 2023-12-26 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cloud_pilot', '0004_netboxdbbackup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='netboxdbbackup',
            options={'verbose_name': 'NetBox DB Backup', 'verbose_name_plural': 'NetBox DB Backups'},
        ),
        migrations.AddField(
            model_name='netboxdbbackup',
            name='netbox_env',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='db_backups', to='netbox_cloud_pilot.netboxconfiguration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='netboxdbbackup',
            name='crontab',
            field=models.CharField(default='@daily', max_length=255),
        ),
    ]
